### ISSUE TITLE
TypeError: slice indices must be integers or None or have an __index__ method

### ISSUE THREAD

**Issue by xiaolaoying** [irlab-sdu/fuzi.mingcha#10]
你好，我在使用cli_demo.py进行任务2基于案例检索时碰到了以下报错：
Traceback (most recent call last):
  File "/home/eagle/fuzi.mingcha/src/cli_demo.py", line 133, in <module>
    main()
  File "/home/eagle/fuzi.mingcha/src/cli_demo.py", line 118, in main
    retrieval_law = retrieval_law + f"第{i + 1}条：\n{doc[-max_len / len(docs):]}\n"
TypeError: slice indices must be integers or None or have an __index__ method

我按照ChatGPT的建议，把这一行改成了：
retrieval_law = retrieval_law + f"第{i + 1}条：\n{doc[-int(max_len / len(docs)):]}\n"

用 int() 函数转换为整数后，可以运行。这里是不是有bug呀？

系统环境：
OS: Ubuntu 22.04.3 LTS
Python 3.10.12

**Comment by zwh-sdu** [comment]
感谢您发现了我们代码存在的错误，这里原本的代码并不严谨，索引可能会出现浮点数，我们会修复这个问题，再次感谢您的提醒。
