### ISSUE TITLE
问下huggingface的模型文件能上传到网盘吗，国内上huggingface拉取不到数据，很难受的。

### ISSUE THREAD

**Issue by san5167** [irlab-sdu/fuzi.mingcha#7]
问下安装Singularity并运行镜像是为什么，没太懂。

**Comment by zwh-sdu** [comment]
pylucene 安装过程比较繁琐，所以我们提供了一个包含 pylucene 环境的镜像。当然也可以使用其他检索方式替代 pylucene，例如 Elasticsearch 或向量检索库。

**Comment by san5167** [comment]
了解了，若是想直接使用对话模型，不用部署Singularity镜像。部署Singularity镜像比跑模型麻烦好多。
谢谢啦，这个模型+检索的法律工具很实用，很棒！！

**Comment by Furyton** [comment]
@san5167 您好，
模型文件已经上传到百度网盘了
链接：https://pan.baidu.com/s/1kEDpBKTj9jX7k1NNhOtEIQ
提取码：ygm1

**Comment by san5167** [comment]
> @san5167 您好， 模型文件已经上传到百度网盘了 链接：https://pan.baidu.com/s/1kEDpBKTj9jX7k1NNhOtEIQ 提取码：ygm1

非常感谢！！
