### ISSUE TITLE
建议修改requirement.txt的transformers版本，transformer按照最新版本4.35.2会出现异常

### ISSUE THREAD

**Issue by san5167** [irlab-sdu/fuzi.mingcha#8]
按照requirement.txt的transformers>=4.29.1,会安装最新版本transformers==4.35.2
![image](https://github.com/irlab-sdu/fuzi.mingcha/assets/116264162/7ce178f4-3792-46ce-a784-bb9c5cb5f760)
运行出现异常：
`AttributeError: 'ChatGLMTokenizer' object has no attribute 'sp_tokenizer'`
![image](https://github.com/irlab-sdu/fuzi.mingcha/assets/116264162/fd2b2276-92c4-435f-85ed-598ee81f9b7d)

建议直接限定transformers版本号，比如transformers==4.33.2，requirement.txt上其他的依赖也建议直接限定版本号。

**Comment by zwh-sdu** [comment]
感谢您的关注，如果 transformers 版本过高确实会存在问题，我们重新修改了 requirement.txt 指定了 transformers 和其他依赖的版本，感谢您的建议。
